// Generated by `pnpm test:e2e:radius:refresh-reference`.
// Level-3 computed border radii captured from local fuwari preview.

export const RADIUS_REFERENCE_BASELINE = {
	"fuwari-navbar-home-link::home-desktop-base::desktop navbar home link": {
		"targetKey": "fuwari-navbar-home-link::home-desktop-base::desktop navbar home link",
		"referenceId": "fuwari-navbar-home-link",
		"label": "desktop navbar home link",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/Navbar.astro:28",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-navbar-nav-link::home-desktop-base::desktop navbar nav link": {
		"targetKey": "fuwari-navbar-nav-link::home-desktop-base::desktop navbar nav link",
		"referenceId": "fuwari-navbar-nav-link",
		"label": "desktop navbar nav link",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/Navbar.astro:37",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-navbar-display-settings-trigger::home-desktop-base::display settings trigger": {
		"targetKey": "fuwari-navbar-display-settings-trigger::home-desktop-base::display settings trigger",
		"referenceId": "fuwari-navbar-display-settings-trigger",
		"label": "display settings trigger",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/Navbar.astro:50",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-light-dark-switch-trigger::home-desktop-base::light dark trigger": {
		"targetKey": "fuwari-light-dark-switch-trigger::home-desktop-base::light dark trigger",
		"referenceId": "fuwari-light-dark-switch-trigger",
		"label": "light dark trigger",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/LightDarkSwitch.svelte:62",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-search-desktop-shell::home-desktop-base::desktop search shell": {
		"targetKey": "fuwari-search-desktop-shell::home-desktop-base::desktop search shell",
		"referenceId": "fuwari-search-desktop-shell",
		"label": "desktop search shell",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/Search.svelte:142",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-profile-about-link::home-desktop-base::sidebar about image link": {
		"targetKey": "fuwari-profile-about-link::home-desktop-base::sidebar about image link",
		"referenceId": "fuwari-profile-about-link",
		"label": "sidebar about image link",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "12px",
		"sourcePath": "src/components/widget/Profile.astro:12",
		"sourceRadius": "rounded-xl"
	},
	"fuwari-categories-button::home-desktop-base::categories widget button": {
		"targetKey": "fuwari-categories-button::home-desktop-base::categories widget button",
		"referenceId": "fuwari-categories-button",
		"label": "categories widget button",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/control/ButtonLink.astro:14",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-categories-badge::home-desktop-base::categories widget badge": {
		"targetKey": "fuwari-categories-badge::home-desktop-base::categories widget badge",
		"referenceId": "fuwari-categories-badge",
		"label": "categories widget badge",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/control/ButtonLink.astro:34",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-tag-chip::home-desktop-base::tags widget chip": {
		"targetKey": "fuwari-tag-chip::home-desktop-base::tags widget chip",
		"referenceId": "fuwari-tag-chip",
		"label": "tags widget chip",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/control/ButtonTag.astro:10",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-inline-link::home-desktop-base::footer rss link": {
		"targetKey": "fuwari-inline-link::home-desktop-base::footer rss link",
		"referenceId": "fuwari-inline-link",
		"label": "footer rss link",
		"path": "/",
		"navigationKey": "home-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "6px",
		"sourcePath": "src/styles/main.css:18",
		"sourceRadius": ".link rounded-md"
	},
	"fuwari-search-mobile-trigger::home-mobile-base::mobile search trigger": {
		"targetKey": "fuwari-search-mobile-trigger::home-mobile-base::mobile search trigger",
		"referenceId": "fuwari-search-mobile-trigger",
		"label": "mobile search trigger",
		"path": "/",
		"navigationKey": "home-mobile-base",
		"viewport": {
			"width": 390,
			"height": 844
		},
		"radiusPx": "7px",
		"sourcePath": "src/components/Search.svelte:155",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-search-panel-shell::home-mobile-search::mobile search panel shell": {
		"targetKey": "fuwari-search-panel-shell::home-mobile-search::mobile search panel shell",
		"referenceId": "fuwari-search-panel-shell",
		"label": "mobile search panel shell",
		"path": "/",
		"navigationKey": "home-mobile-search",
		"viewport": {
			"width": 390,
			"height": 844
		},
		"radiusPx": "14px",
		"sourcePath": "src/components/Search.svelte:161",
		"sourceRadius": "rounded-2xl"
	},
	"fuwari-search-mobile-input-shell::home-mobile-search::mobile search input shell": {
		"targetKey": "fuwari-search-mobile-input-shell::home-mobile-search::mobile search input shell",
		"referenceId": "fuwari-search-mobile-input-shell",
		"label": "mobile search input shell",
		"path": "/",
		"navigationKey": "home-mobile-search",
		"viewport": {
			"width": 390,
			"height": 844
		},
		"radiusPx": "10.5px",
		"sourcePath": "src/components/Search.svelte:164",
		"sourceRadius": "rounded-xl"
	},
	"fuwari-float-panel-shell::home-mobile-nav::mobile nav panel shell": {
		"targetKey": "fuwari-float-panel-shell::home-mobile-nav::mobile nav panel shell",
		"referenceId": "fuwari-float-panel-shell",
		"label": "mobile nav panel shell",
		"path": "/",
		"navigationKey": "home-mobile-nav",
		"viewport": {
			"width": 390,
			"height": 844
		},
		"radiusPx": "14px",
		"sourcePath": "src/styles/main.css:24",
		"sourceRadius": "rounded-[var(--radius-large)]"
	},
	"fuwari-nav-menu-panel-link::home-mobile-nav::mobile nav panel link": {
		"targetKey": "fuwari-nav-menu-panel-link::home-mobile-nav::mobile nav panel link",
		"referenceId": "fuwari-nav-menu-panel-link",
		"label": "mobile nav panel link",
		"path": "/",
		"navigationKey": "home-mobile-nav",
		"viewport": {
			"width": 390,
			"height": 844
		},
		"radiusPx": "7px",
		"sourcePath": "src/components/widget/NavMenuPanel.astro:14",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-float-panel-shell::home-display-settings::display settings panel shell": {
		"targetKey": "fuwari-float-panel-shell::home-display-settings::display settings panel shell",
		"referenceId": "fuwari-float-panel-shell",
		"label": "display settings panel shell",
		"path": "/",
		"navigationKey": "home-display-settings",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "16px",
		"sourcePath": "src/styles/main.css:24",
		"sourceRadius": "rounded-[var(--radius-large)]"
	},
	"fuwari-float-panel-shell::home-theme-panel::light dark panel shell": {
		"targetKey": "fuwari-float-panel-shell::home-theme-panel::light dark panel shell",
		"referenceId": "fuwari-float-panel-shell",
		"label": "light dark panel shell",
		"path": "/",
		"navigationKey": "home-theme-panel",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "16px",
		"sourcePath": "src/styles/main.css:24",
		"sourceRadius": "rounded-[var(--radius-large)]"
	},
	"fuwari-light-dark-panel-option::home-theme-panel::light dark panel option": {
		"targetKey": "fuwari-light-dark-panel-option::home-theme-panel::light dark panel option",
		"referenceId": "fuwari-light-dark-panel-option",
		"label": "light dark panel option",
		"path": "/",
		"navigationKey": "home-theme-panel",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/LightDarkSwitch.svelte:76",
		"sourceRadius": "rounded-lg"
	},
	"fuwari-archive-row-link::archive-desktop-base::archive row link": {
		"targetKey": "fuwari-archive-row-link::archive-desktop-base::archive row link",
		"referenceId": "fuwari-archive-row-link",
		"label": "archive row link",
		"path": "/archive/",
		"navigationKey": "archive-desktop-base",
		"viewport": {
			"width": 1440,
			"height": 900
		},
		"radiusPx": "8px",
		"sourcePath": "src/components/ArchivePanel.svelte:110",
		"sourceRadius": "rounded-lg"
	}
} as const;
