import { writeFile } from "node:fs/promises";
import path from "node:path";

import { expect, test, type Page } from "@playwright/test";

import type { RadiusReferenceBaselineEntry } from "./support/radius-baseline";
import {
	getRadiusTargetKey,
	RADIUS_SOURCE_REFERENCES,
	RUNTIME_RADIUS_BASELINE_TARGETS,
} from "./support/radius-baseline";

const OUTPUT_FILE = path.resolve(
	process.cwd(),
	"tests/e2e/support/radius-baseline.reference.ts",
);

async function prepareReferencePage(page: Page, route: string) {
	await page.addInitScript(() => {
		localStorage.setItem("theme", "light");
		localStorage.setItem("hue", "250");
	});
	await page.goto(route);
	await page.waitForLoadState("networkidle");
	if ((await page.getByRole("heading", { name: "404: Not Found" }).count()) > 0) {
		return false;
	}
	if ((await page.locator("#navbar").count()) === 0) {
		return false;
	}
	await expect(page.locator("#navbar")).toBeVisible();
	await page.waitForLoadState("networkidle");
	await page.addStyleTag({
		content: `
			*,
			*::before,
			*::after {
				animation: none !important;
				transition: none !important;
				scroll-behavior: auto !important;
			}
		`,
	});
	return true;
}

test("capture level-3 radius baseline from local fuwari preview", async ({ page }) => {
	const referenceTargets = RUNTIME_RADIUS_BASELINE_TARGETS.filter((target) => {
		const reference = RADIUS_SOURCE_REFERENCES.find(
			(item) => item.id === target.referenceId,
		);
		return reference?.sourceKind === "fuwari" && reference.runtimeCovered;
	});

	const capturedEntries: Record<string, RadiusReferenceBaselineEntry> = {};
	let currentPath = "";
	let currentNavigationKey = "";
	let currentViewport = { width: 0, height: 0 };
	let currentNavigationAvailable = true;

	for (const target of referenceTargets) {
		const viewportChanged =
			target.viewport.width !== currentViewport.width ||
			target.viewport.height !== currentViewport.height;
		const navigationChanged =
			target.path !== currentPath ||
			target.navigationKey !== currentNavigationKey ||
			viewportChanged;

		if (navigationChanged) {
			await page.setViewportSize(target.viewport);
			currentNavigationAvailable = await prepareReferencePage(page, target.path);
			currentPath = target.path;
			currentNavigationKey = target.navigationKey;
			currentViewport = target.viewport;
		}

		if (!currentNavigationAvailable) {
			continue;
		}

		const prepare = target.referencePrepare ?? target.prepare;
		if (prepare) {
			await prepare(page);
		}

		const reference = RADIUS_SOURCE_REFERENCES.find(
			(item) => item.id === target.referenceId,
		);
		if (!reference) {
			throw new Error(`Missing source reference for ${target.referenceId}`);
		}

		const locator = target.referenceLocate?.(page) ?? target.locate(page);
		if ((await locator.count()) === 0) {
			continue;
		}
		const radiusPx = await locator.evaluate((node) =>
			getComputedStyle(node as HTMLElement).borderTopLeftRadius,
		);
		const targetKey = getRadiusTargetKey(target);
		capturedEntries[targetKey] = {
			targetKey,
			referenceId: target.referenceId,
			label: target.label,
			path: target.path,
			navigationKey: target.navigationKey,
			viewport: target.viewport,
			radiusPx,
			sourcePath: reference.sourcePath,
			sourceRadius: reference.sourceRadius,
		};
	}

	const output = `// Generated by \`pnpm test:e2e:radius:refresh-reference\`.\n` +
		`// Level-3 computed border radii captured from local fuwari preview.\n\n` +
		`export const RADIUS_REFERENCE_BASELINE = ${JSON.stringify(capturedEntries, null, "\t")} as const;\n`;

	await writeFile(OUTPUT_FILE, output, "utf8");
});
